### ISSUE TITLE
Add ability to set the maximum memory size

### ISSUE THREAD

**Issue by jdenderplays** [n-agency/docker-papermc#1]
In other words, a way to use an env variable to control the `-Xmx` flag on the `java` command.
I've tried using docker compose's `mem_limit:` option but it causes java to through all sorts of OutOfMemory errors so it's unreliable.

**Comment by norfair00** [comment]
@jdenderplays  comming on docker hub. Im building images

**Comment by norfair00** [comment]
Done Pushed to Docker hub
